function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------

if(size(im,3)==1)
    % Convert grayscale to RGB
    imrgb(:,:,1) = im;
    imrgb(:,:,2) = im;
    imrgb(:,:,3) = im;
else
    imrgb = im;
end

results.imrgb = imrgb;
%--------------------------------------------------------------------------
